### ISSUE TITLE
new command fetch_rss to add torrents

### ISSUE THREAD

**Issue by micielski** [intuis/rustmission#11]
Could be used together with a cron job.
Transmission doesn't seem to support it natively

**Comment by aidanaden** [comment]
might be better to run in background only while the app is running? think it's a bit intrusive to create a cron job that runs regardless of whether the app is being used (if this is what u mean by "cron job")

**Comment by micielski** [comment]
> might be better to run in background only while the app is running? 

uhh you mean to spawn like a tokio task in the TUI that would check rss feeds in the background while the app is running like every hour?



> think it's a bit intrusive to create a cron job that runs regardless of whether the app is being used

the user would have to do it by himself
this is what [nning/transmission-rss](https://github.com/nning/transmission-rss?tab=readme-ov-file#as-a-cronjob) is doing for example

**Comment by aidanaden** [comment]
> uhh you mean to spawn like a tokio task in the TUI that would check rss feeds in the background while the app is running like every hour?

yep imo this would be preferred

**Comment by aidanaden** [comment]
> the user would have to do it by himself this is what [nning/transmission-rss](https://github.com/nning/transmission-rss?tab=readme-ov-file#as-a-cronjob) is doing for example

nah this is a chore LOL i know it'd definitely be way simple for most users if the app itself would handle refreshing the rss feeds

**Comment by micielski** [comment]
> nah this is a chore LOL i know it'd definitely be way simple for most users if the app itself would handle refreshing the rss feeds

we can support both use cases just fine, in fact implementing the command first will make easier implementing the background fetching
