### ISSUE TITLE
Add ratio in column

### ISSUE THREAD

**Issue by devhell** [intuis/rustmission#121]
Hi! Thank you for this amazing TUI! I love the design and intuitive use.

Are there any plans to add ratio in the column view? This would be helpful for those of us who have ratio configurations set (e.g., 1.5) and just want to glance at how far along all the torrents are in reaching it.

**Comment by micielski** [comment]
Shouldn't be hard, I'll add it in the next couple of days.
Thanks for the suggestion

**Comment by micielski** [comment]
Wait, this is already implemented

Just add "UploadRatio" to headers in `~/.config/rustmission/config.toml` under `[torrents_tab]`

**Comment by micielski** [comment]
@devhell friendly ping to see if that fixes this issue

**Comment by devhell** [comment]
Woah, that's embarrassing! I totally didn't see that in the config! I'm sorry. Thanks for pointing it out (and having it already implemented it)!
