### ISSUE TITLE
bug: selection disappears when scrolled to index `-1` or `n`

### ISSUE THREAD

**Issue by aidanaden** [intuis/rustmission#13]

**Comment by micielski** [comment]
uhh i wasn't thinking about this as a bug, rather a feature - when scrolling down you can't see whether the current selection is the last one, so the disappearance of a selection is the only one currently indicator of this.
the best way to resolve this i think would be if ratatui implemented scroll_padding for Table as for [List](https://docs.rs/ratatui/latest/ratatui/widgets/struct.List.html#method.scroll_padding)

**Comment by aidanaden** [comment]
> uhh i wasn't thinking about this as a bug, rather a feature - when scrolling down you can't see whether the current selection is the last one, so the disappearance of a selection is the only one currently indicator of this. the best way to resolve this i think would be if ratatui implemented scroll_padding for Table as for [List](https://docs.rs/ratatui/latest/ratatui/widgets/struct.List.html#method.scroll_padding)

wouldn't restarting from the other end of the list indicate to the user that the end/start was reached? this happens after the selection disappears anyway .. i just felt confused when the selection disappeared LOL

**Comment by micielski** [comment]
> wouldn't restarting from the other end of the list indicate to the user that the end/start was reached? this happens after the selection disappears anyway .. i just felt confused when the selection disappeared LOL

yeah it may not be the most intuitive thing, but let keep this issue opened till ratatui doesn't implement padding for Table

**Comment by aidanaden** [comment]
we could instead have a counter indicator that displays to the user the current position of the selected item in the list e.g. `12/200` which increments/decrements as the user moves up and down the list

we could place this indicator at the right-hand side of the table header OR at the bottom to the left of the disk size indicator

**Comment by micielski** [comment]
> we could instead have a counter indicator that displays to the user the current position of the selected item in the list e.g. `12/200` which increments/decrements as the user moves up and down the list
> 
> we could place this indicator at the right-hand side of the table header OR at the bottom to the left of the disk size indicator

i like the bottom better, seems like a place for it

**Comment by joshka** [comment]
The next version of ratatui has first, last, next, previous methods on table state and caps the state to 0, items.len() when rendering the table - this might make it possible to remove a bunch of your code. Might be good to throw some feedback about missing things you've had to implement manually in the table if you have time.

**Comment by micielski** [comment]
> Might be good to throw some feedback about missing things you've had to implement manually in the table if you have time.

We've implemented:
- scroll_down_by(amount: usize)
- scroll_up_by(amount: usize)

which could've been just one method, but just with a signed integer. We use them to implement scrolling with PageDown and PageUp.

**Comment by joshka** [comment]
Makes sense. Added https://github.com/ratatui-org/ratatui/issues/1207
