### ISSUE TITLE
feat: add status indication with loading icon to notify user that deletion/move/etc is happening

### ISSUE THREAD

**Issue by aidanaden** [intuis/rustmission#35]
deleting/moving torrent takes a few seconds or more sometimes, displaying an indicator as feedback for the user would help (user might be confused if no deletion happens for longer than 2-3 seconds after pressing "y")

**Comment by micielski** [comment]
I propose to make this happen in rm-main/src/ui/tabs/torrents/tasks, send there the happy outcomes, and handle errors as it is now by sending error_popups.
But after I will refactor transmission action handling

**Comment by aidanaden** [comment]
> I propose to make this happen in rm-main/src/ui/tabs/torrents/tasks, send there the happy outcomes, and handle errors as it is now by sending error_popups. But after I will refactor transmission action handling

will there be a loading indicator? imo that’s the most important otherwise i’m unsure if the deletion/move/action is happening

**Comment by micielski** [comment]
> will there be a loading indicator? 

It would work like in search tab

**Comment by aidanaden** [comment]
> It would work like in search tab

looks good to me !! will find a way to add an animating loading indicator
