### ISSUE TITLE
 Make CLI subcommand add_torrent recognize more types of URLs

### ISSUE THREAD

**Issue by micielski** [intuis/rustmission#5]

**Comment by aidanaden** [comment]
what url types are there other than magnet links?

**Comment by micielski** [comment]
Issue description from codeberg which I forgot to copy here:
currently ./rustmission add-torrent www.example.com/file.torrent will fail

I presume that there's a check in the code like:
```rust
if argument.starts_with("https") {
  // it's a URL
} else {
  // it's a Magnet
}
```

**Comment by aidanaden** [comment]
> Issue description from codeberg which I forgot to copy here: currently ./rustmission add-torrent [www.example.com/file.torrent](http://www.example.com/file.torrent) will fail
> 
> I presume that there's a check in the code like:
> 
> ```rust
> if argument.starts_with("https") {
>   // it's a URL
> } else {
>   // it's a Magnet
> }
> ```

seems like this is a bug in the `transmission_rpc` crate, running their `torrent-add` example results in:

![Uploading Screenshot 2024-06-26 at 4.27.15 AM.png…]()

**Comment by aidanaden** [comment]
seems like this already works? tested with `https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso.torrent`

**Comment by micielski** [comment]
test it with `www.releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso.torrent`
