### ISSUE TITLE
Add CLI command to print default config and keymap to stdout

### ISSUE THREAD

**Issue by micielski** [intuis/rustmission#83]
In case there's a breaking change in the config, the user will have a reference of newest default config / keymap without having to go to github

**Comment by CouldBeFree** [comment]
if I understood you correctly, the user should see the following file content in the console?
``` [general]
# Whether to hide empty columns or not
auto_hide = false

# Possible values: Red, Green, Blue, Yellow, Magenta, Cyan.
# Use prefix "Light" for a brighter color.
# It can also be a hex, e.g. "#3cb371"
accent_color = "LightMagenta"

# If enabled, shows various keybindings throughout the program at the cost of
# a little bit cluttered interface.
beginner_mode = true

# If enabled, hides header row of torrents tab
headers_hide = false

[connection]
url = "http://CHANGE_ME:9091/transmission/rpc" # REQUIRED!

# Refresh timings (in seconds)
torrents_refresh = 5
stats_refresh = 5
free_space_refresh = 10

# If you need username and password to authenticate:
# username = "CHANGE_ME"
# password = "CHANGE_ME"

[torrents_tab]
# Available fields:
# Id, Name, SizeWhenDone, Progress, DownloadRate, UploadRate, DownloadDir,
# Padding, UploadRatio, UploadedEver, AddedDate, ActivityDate, PeersConnected
# SmallStatus
headers = ["Name", "SizeWhenDone", "Progress", "DownloadRate", "UploadRate"]
```

**Comment by micielski** [comment]
Yes! This, and also the keymap (seperate command). If you want to implement this, default configs are currently stored somewhere in rm-config as consts under the name of DEFAULT_CONFIG

**Comment by CouldBeFree** [comment]
I want to try implement this feature. What command name should display the file content?

**Comment by micielski** [comment]
Maybe `print-defaultconfig` and `print-defaultkeymap`?

**Comment by CouldBeFree** [comment]
I tried to run the project locally by running the cargo run command and I got this error
```
Error: error sending request for url (http://change_me:9091/transmission/rpc): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
Is the connection info in "/Users/Oleksandr.Zoria/.config/rustmission/config.toml" correct?
```
How can I configure project locally?

**Comment by micielski** [comment]
You would have to set up Transmission, but that's not really necessary to implement this feature.
Commands that don't interact in any way with Transmission can be run without it, like `rustmission --help`.

**Comment by CouldBeFree** [comment]
@micielski I need some help.
I need to read the config file and do it by using the Rust std library, and I get the raw response I.e. ```"[general]\n# Whether to hide empty columns or not\nauto_hide = false\n\n# Possible values: Red, Green, Blue, Yel...```. If we decide to parse the file in this way, I need to implement some parser to log file content to the console in a readable way. 
There is another option. We can use this crate to parse the toml file https://crates.io/crates/toml. But I have no idea how to add it to the project, when I run this command cargo add toml I get the following error ````cargo add` could not determine which package to modify. Use the `--package` option to specify a package. 
available packages: rustmission, rm-config, rm-shared``` what package should be used if update cli.rust file?
