### ISSUE TITLE
[Question] Does rustmission has a field for download location when adding torrents?

### ISSUE THREAD

**Issue by helixoid** [intuis/rustmission#84]
In the transmission web-ui there is a **field for the download location** when we add any torrent.
It makes sense instead of moving the torrent after adding to the default location.

This is the issue with tremc. **[See here](https://github.com/tremc/tremc/issues/133)**

I really hope rustmission has this feature as I like this project much more than it's python counterpart.

Sorry I am unable to test rustmission as I am out of my hometown and don't have my linux pc with me :(

**Comment by micielski** [comment]
Yes, it's currently implemented only when adding a magnet manually (default key for this is `a` in torrents tab), not when adding a magnet from the search tab (though you could add it and change its location using `m`).
